-- Proyecto POO-BD 01/2021
-- Grupo 4
-- Integrante 1	[00074320	Barahona Hernández, Eddy René]
-- Integrante 2	[00051120	Canales Guillén, Ernesto José]
-- Integrante 3	[00143320	Peraza Bolaños, Víctor Daniel]
-- Integrante 4	[00043920	Ramos Guardado, Diego Fernando]

CREATE DATABASE G4ProyectoDB;
USE G4ProyectoDB;
SET LANGUAGE us_english;

-- Tables section
-- Do not need a FK
CREATE TABLE EFECTO_SECUNDARIO(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	efecto VARCHAR(150) NOT NULL
);

CREATE TABLE CIUDADANO(
	dui VARCHAR(9) NOT NULL PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	numero_identificador VARCHAR(50),
	telefono CHAR(12) NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	correo VARCHAR(100)
);

CREATE TABLE TIPO_EMPLEADO(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	tipo VARCHAR(50) NOT NULL
);

CREATE TABLE CENTRO_VACUNACION(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	direccion VARCHAR(100) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	capacidad INT NOT NULL
);

CREATE TABLE TIPO_DOSIS(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	tipo VARCHAR(50) NOT NULL
);

CREATE TABLE CABINA(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	direccion VARCHAR(100) NOT NULL,
	telefono CHAR(12) NOT NULL,
	correo VARCHAR(25) NOT NULL
);

-- Need a FK
CREATE TABLE ENFERMEDAD(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	enfermedad VARCHAR(50) NOT NULL,
	dui_ciudadano VARCHAR(9) NOT NULL FOREIGN KEY REFERENCES CIUDADANO(dui)
);

CREATE TABLE DISCAPACIDAD(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	discapacidad VARCHAR(50) NOT NULL,
	dui_ciudadano VARCHAR(9) NOT NULL FOREIGN KEY REFERENCES CIUDADANO(dui)
);

CREATE TABLE PROCESO_DE_VACUNACION(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	fecha DATE NOT NULL,
	hora_inicio TIME NOT NULL,
	hora_vacunacion TIME NOT NULL,
	hora_final TIME NOT NULL,
	tipo_dosis INT NOT NULL FOREIGN KEY REFERENCES TIPO_DOSIS(id),
	dui_ciudadano VARCHAR(9) NOT NULL FOREIGN KEY REFERENCES CIUDADANO(dui)
);

CREATE TABLE EMPLEADO(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	usuario VARCHAR(50) NOT NULL,
	contrasena VARCHAR(50) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	direccion VARCHAR(100) NOT NULL,
	correo VARCHAR(25) NOT NULL,
	id_tipo INT NOT NULL FOREIGN KEY REFERENCES TIPO_EMPLEADO(id)
);

CREATE TABLE CITA(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	fecha DATETIME NOT NULL,
	tipo_dosis INT NOT NULL FOREIGN KEY REFERENCES TIPO_DOSIS(id),
	id_centro INT NOT NULL FOREIGN KEY REFERENCES CENTRO_VACUNACION(id),
	dui_ciudadano VARCHAR(9) NOT NULL FOREIGN KEY REFERENCES CIUDADANO(dui),
	id_empleado INT NOT NULL FOREIGN KEY REFERENCES EMPLEADO(id)
);

CREATE TABLE SESION(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	fecha DATETIME NOT NULL,
	id_empleado INT NOT NULL FOREIGN KEY REFERENCES EMPLEADO(id),
	id_cabina INT NOT NULL FOREIGN KEY REFERENCES CABINA(id)
);

CREATE TABLE EFECTO_PRESENTADO(
	id INT PRIMARY KEY IDENTITY,
	tiempo_aparicion INT NOT NULL,
	id_proceso_vacunacion INT NOT NULL FOREIGN KEY REFERENCES PROCESO_DE_VACUNACION(id),
	id_efecto_secundario INT NOT NULL FOREIGN KEY REFERENCES EFECTO_SECUNDARIO(id)
);

-- Need a PK-FK
CREATE TABLE ENCARGADO(
	id_empleado INT NOT NULL,
	id_cabina INT NOT NULL,
	CONSTRAINT PK_encargado PRIMARY KEY (id_empleado, id_cabina),
	FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id),
	FOREIGN KEY (id_cabina) REFERENCES CABINA(id)
);

-- NOTES:
-- DATE: format YYYY-MM-DD
-- TIME: format hh:mm:ss
-- telefono CHAR(12): +50300000000

-- Inserting data to tables
-- EFECTO_SECUNDARIO
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Dolor y/o sensibilidad en el sitio de la inyección.');
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Enrojecimiento en el sitio de la inyección.');
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Fatiga');
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Dolor de cabeza');
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Fiebre');
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Mialgia');
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Artralgia');
INSERT INTO EFECTO_SECUNDARIO
	VALUES ('Anafilaxia');

-- TIPO_EMPLEADO
INSERT INTO TIPO_EMPLEADO
	VALUES('Administrador/Encargado');
INSERT INTO TIPO_EMPLEADO
	VALUES('Gestor');

-- CENTRO_VACUNACION
INSERT INTO CENTRO_VACUNACION
	VALUES('4945 Purus. St.', 'Mega Centro de Vacunación', 1000);
INSERT INTO CENTRO_VACUNACION
	VALUES('5249 Lobortis St.', 'Centro de Salud General', 200);
INSERT INTO CENTRO_VACUNACION
	VALUES('P.O. Box 772, 6980 Faucibus. St.', 'ISSS Santa Tecla', 100);
INSERT INTO CENTRO_VACUNACION
	VALUES('3067 Nec Road', 'Fundación Juan Carlos Bodoque', 3500);
INSERT INTO CENTRO_VACUNACION
	VALUES('Ap #684-4488 Dui St.', 'Hospital General EEVD', 80);
INSERT INTO CENTRO_VACUNACION
	VALUES('202-3173 In Avenue', 'Vacunación La Gran Vía', 10);

-- TIPO_DOSIS
INSERT INTO TIPO_DOSIS
	VALUES('Primera dosis');
INSERT INTO TIPO_DOSIS
	VALUES('Segunda dosis');

-- CABINA
INSERT INTO CABINA
	VALUES('4945 Purus. St.', '+50323235687', 'Purus@gmail.com');
INSERT INTO CABINA
	VALUES('5249 Lobortis St.', '+50398453214', 'Lobortis@yahoo.es');
INSERT INTO CABINA
	VALUES('P.O. Box 772, 6980 Faucibus. St.', '+50324242424', 'Faucibus@gmail.gov.sv');
INSERT INTO CABINA
	VALUES('3067 Nec Road', '+50371529846', 'Nec_Road@gmail.com');
INSERT INTO CABINA
	VALUES('Ap #684-4488 Dui St.', '+50398632541', 'dui@hotmail.com');
INSERT INTO CABINA
	VALUES('202-3173 In Avenue', '+50377436852', 'InAv@yahoo.com');
INSERT INTO CABINA
	VALUES('4355 Santa Ana', '+50396318542', 'santa_ana@gmail.gov.sv');
INSERT INTO CABINA
	VALUES('P.O. Box 354, 4543 La Unión', '+50322436578', 'union@uca.edu.sv');
INSERT INTO CABINA
	VALUES('5654 San Julian Av.', '+50323864571', 'SanJu@hotmail.com');
INSERT INTO CABINA
	VALUES('45345 Cojutepeque St.', '+50376482514', 'cojute14@gmail.com');

-- EMPLEADO
INSERT INTO EMPLEADO
	VALUES('Gestor_01', 'ABC123', 'Holo', 'Yoitsu Village', 'holo537@gmail.com', 1);
INSERT INTO EMPLEADO
	VALUES('Root', 'Admin', 'Kraft Lawrence', '5213 Pazzio City', 'kraft@yahoo.com', 2);

-- ENCARGADO
INSERT INTO ENCARGADO
	VALUES(2, 5);